"""add member id column on payment table

Revision ID: 65f017e3af56
Revises: 991a8a0f47cf
Create Date: 2025-11-08 11:07:03.998251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65f017e3af56"
down_revision: Union[str, Sequence[str], None] = "991a8a0f47cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("member_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, "payment", "member", ["member_id"], ["member_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_column("payment", "member_id")
    # ### end Alembic commands ###
